### ISSUE TITLE
Organization does not get deleted

### ISSUE THREAD

**Issue by devinercolano** [Cadasta/ckanext-project#62] opened 2015-10-28 16:26 UTC
--reproduction steps--

-Log into Cadasta

-Navigate to 'organizations'

-create a new organization
![creatingorganization](https://cloud.githubusercontent.com/assets/4064770/10795158/a7c8c510-7d55-11e5-9280-1d88fff99d73.png)

-delete that organization
*see "organization has been deleted message"
![interface_says_org_deleted](https://cloud.githubusercontent.com/assets/4064770/10795166/af8f1286-7d55-11e5-8c90-e88b90497a51.png)

-try to create an organization with the same name
*see "Organization name already exists" message
![organization was not deleted](https://cloud.githubusercontent.com/assets/4064770/10795168/b489849c-7d55-11e5-9711-fa9fb3730f20.png)

--expected result--
-Expected that after deleting the organization it's name could be reused.

--actual result--
-Cannot re-use an organization name, even if it has been deleted.

**Comment by rgwozdz** [comment] 2015-10-28 17:18
This occurs because CKAN app does not really “delete” an organization, it actually “archives” it.  It is still stored in the database, and as a result, you cannot use the organization name over again.  This is less of a bug and more of an issue of relabeling the “delete” button and giving the proper messaging that you can create a new organization with the same name of an archived organization.


On Oct 28, 2015, at 9:26 AM, Devin Ercolano <notifications@github.com<mailto:notifications@github.com>> wrote:


--reproduction steps--

-Log into Cadasta

-Navigate to 'organizations'

-create a new organization
[creatingorganization]<https://cloud.githubusercontent.com/assets/4064770/10795158/a7c8c510-7d55-11e5-9280-1d88fff99d73.png>

-delete that organization
*see "organization has been deleted message"
[interface_says_org_deleted]<https://cloud.githubusercontent.com/assets/4064770/10795166/af8f1286-7d55-11e5-8c90-e88b90497a51.png>

-try to create an organization with the same name
*see "Organization name already exists" message
[organization was not deleted]<https://cloud.githubusercontent.com/assets/4064770/10795168/b489849c-7d55-11e5-9711-fa9fb3730f20.png>

--expected result--
-Expected that after deleting the organization it's name could be reused.

--actual result--
-Cannot re-use an organization name, even if it has been deleted.

**Comment by rgwozdz** [comment] 2015-10-28 18:27
I'm going to close this and open as an issue with my comment above.

**Comment by rgwozdz** [comment] 2015-10-28 18:49
see #65 and #64

**Closed by rgwozdz** 2015-10-28 18:49 UTC
Labels: enhancement
